import { describe, expect, it } from 'vitest';
import { applyUnifiedDiff, diffLines, formatUnifiedDiff, parseUnifiedDiff, splitLines } from './diff.js';

const ORIGINAL = ['alpha', 'beta', 'gamma', 'delta', 'epsilon'].join('\n') + '\n';

describe('splitLines', () => {
  it('drops the trailing newline terminator', () => {
    expect(splitLines('a\nb\n')).toEqual(['a', 'b']);
  });

  it('normalises CRLF', () => {
    expect(splitLines('a\r\nb\r\n')).toEqual(['a', 'b']);
  });
});

describe('diffLines', () => {
  it('reports additions and deletions', () => {
    const result = diffLines(ORIGINAL, ['alpha', 'BETA', 'gamma', 'delta', 'epsilon'].join('\n') + '\n');
    expect(result.additions).toBe(1);
    expect(result.deletions).toBe(1);
    expect(result.hunks).toHaveLength(1);
  });

  it('detects pure insertions', () => {
    const result = diffLines('a\nb\n', 'a\nb\nc\n');
    expect(result.additions).toBe(1);
    expect(result.deletions).toBe(0);
    expect(result.hunks[0]!.oldLines).toBe(2);
    expect(result.hunks[0]!.newLines).toBe(3);
  });

  it('returns no hunks for identical text', () => {
    expect(diffLines(ORIGINAL, ORIGINAL).hunks).toHaveLength(0);
  });

  it('produces non-overlapping hunks', () => {
    const before = Array.from({ length: 60 }, (_, i) => `line ${i}`).join('\n') + '\n';
    const after = before
      .replace('line 5', 'CHANGED 5')
      .replace('line 40', 'CHANGED 40');

    const hunks = diffLines(before, after).hunks;
    expect(hunks).toHaveLength(2);

    for (let i = 1; i < hunks.length; i += 1) {
      const previous = hunks[i - 1]!;
      const current = hunks[i]!;
      // The next hunk must start strictly after the previous one ends.
      expect(current.oldStart).toBeGreaterThan(previous.oldStart + previous.oldLines);
    }
  });

  it('degrades to a block replace for very large inputs', () => {
    const a = Array.from({ length: 4000 }, (_, i) => `a${i}`).join('\n');
    const b = Array.from({ length: 4000 }, (_, i) => `b${i}`).join('\n');
    const result = diffLines(a, b, { maxCells: 1000 });
    expect(result.additions).toBe(4000);
    expect(result.deletions).toBe(4000);
  });
});

describe('formatUnifiedDiff', () => {
  it('emits a standard header and hunk marker', () => {
    const diff = formatUnifiedDiff('src/a.ts', 'a\nb\nc\n', 'a\nB\nc\n');
    expect(diff).toContain('--- a/src/a.ts');
    expect(diff).toContain('+++ b/src/a.ts');
    expect(diff).toMatch(/@@ -\d+,\d+ \+\d+,\d+ @@/);
    expect(diff).toContain('-b');
    expect(diff).toContain('+B');
  });
});

describe('applyUnifiedDiff', () => {
  it('round-trips a diff generated by formatUnifiedDiff', () => {
    const before = 'one\ntwo\nthree\nfour\nfive\n';
    const after = 'one\ntwo\nTHREE\nfour\nfive\n';
    const diff = formatUnifiedDiff('f.txt', before, after);

    const result = applyUnifiedDiff(before, diff);
    expect(result.ok).toBe(true);
    expect(result.content).toBe(after);
  });

  it('applies several hunks at once', () => {
    const before = Array.from({ length: 30 }, (_, i) => `line ${i}`).join('\n') + '\n';
    const after = before.replace('line 2', 'X').replace('line 25', 'Y');
    const result = applyUnifiedDiff(before, formatUnifiedDiff('f.txt', before, after));
    expect(result.ok).toBe(true);
    expect(result.content).toBe(after);
  });

  it('handles pure insertion hunks', () => {
    const before = 'a\nb\n';
    const after = 'a\nb\nc\n';
    const result = applyUnifiedDiff(before, formatUnifiedDiff('f.txt', before, after));
    expect(result.content).toBe(after);
  });

  it('tolerates small line drift via fuzz', () => {
    const before = Array.from({ length: 40 }, (_, i) => `line ${i}`).join('\n') + '\n';
    const after = before.replace('line 20', 'CHANGED');
    const diff = formatUnifiedDiff('f.txt', before, after);

    // Shift the recorded hunk position by a few lines.
    const shifted = diff.replace(/@@ -(\d+),/, (_match, start: string) => `@@ -${Number(start) + 3},`);
    const result = applyUnifiedDiff(before, shifted, { fuzz: 40 });
    expect(result.ok).toBe(true);
    expect(result.content).toBe(after);
  });

  it('fails cleanly when the target text is absent', () => {
    const result = applyUnifiedDiff('a\nb\nc\n', '--- a/f\n+++ b/f\n@@ -1,3 +1,3 @@\n-zed\n-yak\n+qux\n');
    expect(result.ok).toBe(false);
    expect(result.error).toMatch(/could not be applied/);
    expect(result.content).toBe('a\nb\nc\n');
  });

  it('rejects a diff with no hunks', () => {
    const result = applyUnifiedDiff('a\n', 'not a diff at all');
    expect(result.ok).toBe(false);
  });
});

describe('parseUnifiedDiff', () => {
  it('extracts the target path from the +++ header', () => {
    const parsed = parseUnifiedDiff('--- a/src/x.ts\n+++ b/src/x.ts\n@@ -1,1 +1,1 @@\n-a\n+b\n');
    expect(parsed.filePath).toBe('src/x.ts');
    expect(parsed.hunks).toHaveLength(1);
    expect(parsed.hunks[0]!.lines.map((l) => l.type)).toEqual(['remove', 'add']);
  });
});
