import type { SkillManifest } from '@cluster/shared';

/**
 * Built-in & Marketplace Skill Catalog for Cluster.
 * Covers all 16 diverse categories:
 * coding, refactor, review, debugging, docs, ui, electron, memory,
 * provider, workflow, automation, planning, testing, deployment, project_setup, migration.
 */
export const MARKETPLACE_CATALOG: SkillManifest[] = [
  {
    id: 'refactor-clean',
    name: 'refactor-clean',
    displayName: 'Clean Architecture Refactoring Engine',
    version: '1.2.0',
    description: 'Analyzes complex codebases and executes SOLID, DRY, and clean layered refactoring with zero behavioral breakage.',
    author: 'Cluster Core Team',
    tags: ['refactor', 'clean-code', 'solid', 'architecture'],
    category: 'refactor',
    entryType: 'workflow',
    invocationName: 'refactor',
    supportedCommands: ['/refactor', '/refactor-clean'],
    requiredPermissions: ['fs:read', 'fs:write', 'cmd:exec'],
    requiredTools: ['read_file', 'write_file', 'patch_file', 'run_command'],
    modelCompatibility: 'all',
    installSource: 'builtin',
    instructions: [
      '### Clean Architecture Refactoring Directive',
      'When this skill is invoked:',
      '1. Read the target files carefully and identify code smells: high cyclomatic complexity, tight coupling, duplicated logic, and violation of single responsibility.',
      '2. Plan an incremental refactoring strategy that preserves public interfaces and backwards compatibility.',
      '3. Extract discrete domain functions and strongly-typed models.',
      '4. Use patch_file or write_file to apply changes surgically one file at a time.',
      '5. Verify by running the project tests or build commands after refactoring.',
    ].join('\n'),
    workflow: [
      { id: 'step-1', title: 'Analyze target files for architectural smells', action: 'Inspect structure and calculate cyclomatic complexity' },
      { id: 'step-2', title: 'Formulate safe refactoring plan', action: 'Design modular layers and decouple dependencies' },
      { id: 'step-3', title: 'Apply surgical code improvements', action: 'Execute refactoring file by file' },
      { id: 'step-4', title: 'Verify and run test suite', action: 'Confirm zero regression in tests and builds' },
    ],
    securityFlags: { isVerified: true, isSafe: true, communityReviewed: true },
    stats: { downloads: 4820, rating: 4.95, invocations: 1240 },
    icon: 'Layers',
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'test-suite-gen',
    name: 'test-suite-gen',
    displayName: 'Vitest / Jest Test Suite Generator',
    version: '2.0.1',
    description: 'Generates comprehensive unit, integration, and edge-case test suites with high branch coverage and mocking.',
    author: 'Cluster Core Team',
    tags: ['testing', 'vitest', 'jest', 'unit-tests', 'coverage'],
    category: 'testing',
    entryType: 'workflow',
    invocationName: 'testgen',
    supportedCommands: ['/testgen', '/test-suite'],
    requiredPermissions: ['fs:read', 'fs:write', 'cmd:exec'],
    requiredTools: ['read_file', 'write_file', 'patch_file', 'run_command'],
    modelCompatibility: 'all',
    installSource: 'builtin',
    instructions: [
      '### Test Suite Generation Directive',
      'When this skill is invoked:',
      '1. Read the implementation file to determine all exported symbols, functions, types, and edge cases.',
      '2. Inspect existing test configurations (vitest.config.ts, jest.config.js) to match conventions.',
      '3. Write a thorough test file covering: happy path, boundary values, error conditions, and null/undefined handling.',
      '4. Run `npm test` or the appropriate test command to verify that all written tests pass immediately.',
    ].join('\n'),
    securityFlags: { isVerified: true, isSafe: true, communityReviewed: true },
    stats: { downloads: 3950, rating: 4.9, invocations: 920 },
    icon: 'CheckCircle2',
    createdAt: '2026-08-05T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'api-doc-writer',
    name: 'api-doc-writer',
    displayName: 'OpenAPI & Markdown API Doc Generator',
    version: '1.1.0',
    description: 'Extracts endpoints, types, schemas, and usage examples from code and generates rich documentation.',
    author: 'DevDocs Community',
    tags: ['docs', 'api', 'markdown', 'openapi', 'swagger'],
    category: 'docs',
    entryType: 'prompt',
    invocationName: 'docs',
    supportedCommands: ['/docs', '/api-docs'],
    requiredPermissions: ['fs:read', 'fs:write'],
    requiredTools: ['read_file', 'write_file'],
    modelCompatibility: 'all',
    installSource: 'builtin',
    instructions: [
      '### API Documentation Directive',
      'Inspect the route handlers, schemas, and controllers.',
      'Generate clear, comprehensive documentation including:',
      '- Endpoint URL, HTTP method, and authentication requirements',
      '- Request headers, query params, and JSON body schema',
      '- Success and error response models with sample JSON payloads',
      '- cURL and TypeScript SDK usage snippets',
    ].join('\n'),
    securityFlags: { isVerified: true, isSafe: true, communityReviewed: true },
    stats: { downloads: 2600, rating: 4.8, invocations: 530 },
    icon: 'FileText',
    createdAt: '2026-08-10T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'bug-hunter',
    name: 'bug-hunter',
    displayName: 'Root-Cause Bug Hunter & Stack Diagnoser',
    version: '2.1.0',
    description: 'Diagnoses tricky runtime bugs, memory leaks, unhandled exceptions, and race conditions with surgical precision.',
    author: 'Cluster Diagnostics',
    tags: ['debugging', 'bugfix', 'stacktrace', 'diagnostics'],
    category: 'debugging',
    entryType: 'workflow',
    invocationName: 'debug',
    supportedCommands: ['/debug', '/bug-hunter'],
    requiredPermissions: ['fs:read', 'fs:write', 'cmd:exec'],
    requiredTools: ['read_file', 'write_file', 'patch_file', 'run_command'],
    modelCompatibility: 'all',
    installSource: 'builtin',
    instructions: [
      '### Root Cause Bug Hunting Protocol',
      '1. Read the error trace or description provided by the user.',
      '2. Inspect the exact file and line number where the failure occurred.',
      '3. Trace caller functions and data flow upstream to identify root causes rather than just band-aiding symptoms.',
      '4. Patch the issue surgically, and run tests or build commands to prove the fix works.',
      '5. Explain what caused the bug, why the fix works, and how to avoid it in the future.',
    ].join('\n'),
    securityFlags: { isVerified: true, isSafe: true, communityReviewed: true },
    stats: { downloads: 5120, rating: 4.98, invocations: 1650 },
    icon: 'Bug',
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-09-02T00:00:00.000Z',
  },
  {
    id: 'ui-tailwind-framer',
    name: 'ui-tailwind-framer',
    displayName: 'Tailwind + Framer Motion UI Builder',
    version: '1.4.0',
    description: 'Builds beautiful, responsive, modern dark-mode UI components using Tailwind CSS and Framer Motion animations.',
    author: 'Design Systems Lab',
    tags: ['ui', 'tailwind', 'framer-motion', 'components', 'design'],
    category: 'ui',
    entryType: 'prompt',
    invocationName: 'ui',
    supportedCommands: ['/ui', '/component'],
    requiredPermissions: ['fs:read', 'fs:write'],
    requiredTools: ['read_file', 'write_file', 'patch_file'],
    modelCompatibility: 'all',
    installSource: 'builtin',
    instructions: [
      '### Modern UI & Motion Directive',
      'Build modern UI components adhering to:',
      '- Dark theme aesthetics: soft ambient borders (#22222a), deep backgrounds (#0c0c0f, #121218), subtle accent glows.',
      '- Framer Motion animations: smooth spring transitions, hover states, layout animations without layout jank.',
      '- Accessible, semantic HTML elements with keyboard navigability.',
      '- Mobile-responsive grid and flex layouts.',
    ].join('\n'),
    securityFlags: { isVerified: true, isSafe: true, communityReviewed: true },
    stats: { downloads: 4400, rating: 4.92, invocations: 1100 },
    icon: 'Palette',
    createdAt: '2026-08-12T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'electron-desktop-architect',
    name: 'electron-desktop-architect',
    displayName: 'Electron Desktop & IPC Architect',
    version: '1.3.0',
    description: 'Specialist for Electron desktop apps: typed contextBridge IPC, native dialogs, window controls, and packaging.',
    author: 'Cluster Desktop Team',
    tags: ['electron', 'desktop', 'ipc', 'preload', 'packaging'],
    category: 'electron',
    entryType: 'workflow',
    invocationName: 'electron',
    supportedCommands: ['/electron', '/desktop'],
    requiredPermissions: ['fs:read', 'fs:write', 'cmd:exec'],
    requiredTools: ['read_file', 'write_file', 'patch_file', 'run_command'],
    modelCompatibility: 'all',
    installSource: 'builtin',
    instructions: [
      '### Electron Architecture Directive',
      'Design and audit Electron features using best practices:',
      '- Strict context isolation: never expose `ipcRenderer` directly; use typed `contextBridge.exposeInMainWorld`.',
      '- Handle asynchronous IPC with `ipcMain.handle` and `ipcRenderer.invoke`.',
      '- Support multi-platform packaging (electron-builder, NSIS Windows installers, macOS dmg).',
      '- Keep main process non-blocking and delegate heavy compute to worker threads or child processes.',
    ].join('\n'),
    securityFlags: { isVerified: true, isSafe: true, communityReviewed: true },
    stats: { downloads: 2900, rating: 4.88, invocations: 640 },
    icon: 'AppWindow',
    createdAt: '2026-08-15T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'sqlite-vec-memory',
    name: 'sqlite-vec-memory',
    displayName: 'SQLite & Vector Memory Optimization',
    version: '1.0.5',
    description: 'Inspects, tunes, and optimizes SQLite vector databases, embedding dimensions, and hybrid retrieval scoring.',
    author: 'Cluster Memory Team',
    tags: ['memory', 'sqlite', 'sqlite-vec', 'embeddings', 'retrieval'],
    category: 'memory',
    entryType: 'prompt',
    invocationName: 'memory-tune',
    supportedCommands: ['/memory-tune', '/memory'],
    requiredPermissions: ['fs:read', 'fs:write', 'memory'],
    requiredTools: ['read_file', 'write_file'],
    modelCompatibility: 'all',
    installSource: 'builtin',
    instructions: [
      '### Memory Subsystem Tuning Directive',
      'Analyze the project memory schema and vector indexing.',
      'Provide recommendations and migrations for cosine similarity search, importance weighting, and durable context extraction.',
    ].join('\n'),
    securityFlags: { isVerified: true, isSafe: true },
    stats: { downloads: 1800, rating: 4.85, invocations: 310 },
    icon: 'Brain',
    createdAt: '2026-08-20T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'code-review-security',
    name: 'code-review-security',
    displayName: 'Security Audit & OWASP Scanner',
    version: '2.0.0',
    description: 'Scans source code for command injection, path traversal, hardcoded secrets, prototype pollution, and OWASP risks.',
    author: 'SecOps Team',
    tags: ['review', 'security', 'owasp', 'audit', 'cve'],
    category: 'review',
    entryType: 'workflow',
    invocationName: 'review',
    supportedCommands: ['/review', '/security-audit'],
    requiredPermissions: ['fs:read'],
    requiredTools: ['read_file', 'search_text'],
    modelCompatibility: 'all',
    installSource: 'builtin',
    instructions: [
      '### Security & Vulnerability Review Protocol',
      'Inspect changed files and repository security surface:',
      '1. Check for command injection (unvalidated exec, child_process, shell concatenation).',
      '2. Check for path traversal (resolveWithoutEscape, ../ paths).',
      '3. Check for exposed API keys, bearer tokens, or sensitive credentials in git history.',
      '4. Deliver a prioritized checklist: Critical, High, Medium, and Low risk findings with remediation diffs.',
    ].join('\n'),
    securityFlags: { isVerified: true, isSafe: true, communityReviewed: true },
    stats: { downloads: 3700, rating: 4.93, invocations: 850 },
    icon: 'ShieldCheck',
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'git-workflow-pro',
    name: 'git-workflow-pro',
    displayName: 'Git Workflow & Conventional Commits Pro',
    version: '1.1.2',
    description: 'Manages git branch workflows, generates conventional commit messages from diffs, and creates release changelogs.',
    author: 'Git Flow Community',
    tags: ['workflow', 'git', 'commit', 'changelog', 'release'],
    category: 'workflow',
    entryType: 'tool',
    invocationName: 'git',
    supportedCommands: ['/git', '/commit'],
    requiredPermissions: ['cmd:exec', 'fs:read'],
    requiredTools: ['git_status', 'run_command'],
    modelCompatibility: 'all',
    installSource: 'builtin',
    instructions: [
      '### Git Workflow Directive',
      'Inspect git status and uncommitted diffs.',
      'Group related changes into logical atomic commits following the Conventional Commits standard (feat:, fix:, chore:, refactor:).',
    ].join('\n'),
    securityFlags: { isVerified: true, isSafe: true },
    stats: { downloads: 3100, rating: 4.87, invocations: 780 },
    icon: 'GitBranch',
    createdAt: '2026-08-08T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'schema-validator',
    name: 'schema-validator',
    displayName: 'Zod & TypeScript Schema Architect',
    version: '1.2.0',
    description: 'Generates robust Zod validation schemas, TypeScript interfaces, and bidirectional type parsers.',
    author: 'TypeSafe Team',
    tags: ['coding', 'zod', 'typescript', 'validation', 'types'],
    category: 'coding',
    entryType: 'prompt',
    invocationName: 'schema',
    supportedCommands: ['/schema', '/zod'],
    requiredPermissions: ['fs:read', 'fs:write'],
    requiredTools: ['read_file', 'write_file', 'patch_file'],
    modelCompatibility: 'all',
    installSource: 'builtin',
    instructions: [
      '### Schema Design Directive',
      'Build end-to-end type-safe Zod schemas with custom refinements, error formatting, and type inference.',
    ].join('\n'),
    securityFlags: { isVerified: true, isSafe: true },
    stats: { downloads: 2200, rating: 4.89, invocations: 490 },
    icon: 'Code',
    createdAt: '2026-08-14T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'performance-profiler',
    name: 'performance-profiler',
    displayName: 'Bundle & Runtime Performance Profiler',
    version: '1.0.8',
    description: 'Identifies expensive re-renders, bloated bundle chunks, unindexed queries, and CPU bottlenecks.',
    author: 'PerfLabs',
    tags: ['automation', 'performance', 'profiler', 'bundle', 'optimization'],
    category: 'automation',
    entryType: 'workflow',
    invocationName: 'perf',
    supportedCommands: ['/perf', '/optimize'],
    requiredPermissions: ['fs:read', 'cmd:exec'],
    requiredTools: ['read_file', 'run_command'],
    modelCompatibility: 'all',
    installSource: 'marketplace',
    instructions: [
      '### Performance Profiling Directive',
      'Analyze bundle sizes and render bottlenecks. Propose code-splitting, memoization, and lazy loading strategies.',
    ].join('\n'),
    securityFlags: { isVerified: true, isSafe: true },
    stats: { downloads: 1540, rating: 4.79, invocations: 280 },
    icon: 'Zap',
    createdAt: '2026-08-22T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'migration-assistant',
    name: 'migration-assistant',
    displayName: 'Framework & Library Migration Assistant',
    version: '1.1.0',
    description: 'Automates migrations between major framework versions (e.g. React 18 to 19, Vite, Tailwind v3 to v4, Next.js).',
    author: 'MigrateHQ',
    tags: ['migration', 'upgrade', 'framework', 'breaking-changes'],
    category: 'migration',
    entryType: 'workflow',
    invocationName: 'migrate',
    supportedCommands: ['/migrate', '/upgrade'],
    requiredPermissions: ['fs:read', 'fs:write', 'cmd:exec'],
    requiredTools: ['read_file', 'write_file', 'patch_file', 'run_command'],
    modelCompatibility: 'all',
    installSource: 'marketplace',
    instructions: [
      '### Migration Protocol',
      '1. Read package.json to identify current versions and peer dependency constraints.',
      '2. Formulate step-by-step upgrade plan addressing breaking changes.',
      '3. Update package declarations and run installation.',
      '4. Adapt code for deprecated APIs and verify build.',
    ].join('\n'),
    securityFlags: { isVerified: true, isSafe: true },
    stats: { downloads: 1980, rating: 4.82, invocations: 390 },
    icon: 'RefreshCw',
    createdAt: '2026-08-18T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'project-scaffold',
    name: 'project-scaffold',
    displayName: 'Full-Stack Project Scaffolder',
    version: '1.2.5',
    description: 'Scaffolds complete, production-ready full-stack projects with TypeScript, Tailwind, ESLint, and test setups.',
    author: 'Cluster Core Team',
    tags: ['project_setup', 'scaffold', 'bootstrap', 'fullstack'],
    category: 'project_setup',
    entryType: 'workflow',
    invocationName: 'scaffold',
    supportedCommands: ['/scaffold', '/init-project'],
    requiredPermissions: ['fs:read', 'fs:write', 'cmd:exec'],
    requiredTools: ['write_file', 'run_command'],
    modelCompatibility: 'all',
    installSource: 'builtin',
    instructions: [
      '### Project Scaffolding Directive',
      'Scaffold clean project architectures with modern build tooling, type checking, and modular directory structures.',
    ].join('\n'),
    securityFlags: { isVerified: true, isSafe: true, communityReviewed: true },
    stats: { downloads: 3400, rating: 4.91, invocations: 710 },
    icon: 'FolderPlus',
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'ci-cd-deploy',
    name: 'ci-cd-deploy',
    displayName: 'CI/CD & Docker Deployment Pipeline Builder',
    version: '1.0.4',
    description: 'Creates optimized Dockerfiles, multi-stage builds, and GitHub Actions CI/CD workflows for automated testing and releases.',
    author: 'DevOps Guild',
    tags: ['deployment', 'docker', 'ci-cd', 'github-actions'],
    category: 'deployment',
    entryType: 'prompt',
    invocationName: 'deploy',
    supportedCommands: ['/deploy', '/ci-cd', '/docker'],
    requiredPermissions: ['fs:read', 'fs:write'],
    requiredTools: ['read_file', 'write_file'],
    modelCompatibility: 'all',
    installSource: 'marketplace',
    instructions: [
      '### CI/CD & Deployment Directive',
      'Generate production Dockerfiles with non-root security users, multi-stage caching, and GitHub Actions workflows.',
    ].join('\n'),
    securityFlags: { isVerified: true, isSafe: true },
    stats: { downloads: 1720, rating: 4.86, invocations: 310 },
    icon: 'Cloud',
    createdAt: '2026-08-25T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
  {
    id: 'architect-planner',
    name: 'architect-planner',
    displayName: 'Deep Spec & RFC Technical Planner',
    version: '2.0.0',
    description: 'Generates comprehensive architectural RFCs, technical specs, risk registers, and step-by-step rollout plans.',
    author: 'Cluster Core Team',
    tags: ['planning', 'rfc', 'spec', 'architecture', 'strategy'],
    category: 'planning',
    entryType: 'prompt',
    invocationName: 'architect',
    supportedCommands: ['/architect', '/plan-spec'],
    requiredPermissions: ['fs:read', 'memory'],
    requiredTools: ['read_file'],
    modelCompatibility: 'all',
    installSource: 'builtin',
    instructions: [
      '### Deep Architectural Spec Protocol',
      'Formulate comprehensive technical RFCs with problem definitions, trade-off matrix, component boundaries, and migration paths.',
    ].join('\n'),
    securityFlags: { isVerified: true, isSafe: true, communityReviewed: true },
    stats: { downloads: 4100, rating: 4.96, invocations: 1050 },
    icon: 'Compass',
    createdAt: '2026-08-01T00:00:00.000Z',
    updatedAt: '2026-09-02T00:00:00.000Z',
  },
  {
    id: 'provider-router',
    name: 'provider-router',
    displayName: 'Multi-LLM Provider & Cost Optimizer',
    version: '1.0.2',
    description: 'Recommends the best LLM provider and model for each task type, balancing token cost, latency, and reasoning capability.',
    author: 'Cluster AI Lab',
    tags: ['provider', 'llm', 'routing', 'cost', 'optimization'],
    category: 'provider',
    entryType: 'prompt',
    invocationName: 'model-route',
    supportedCommands: ['/model-route', '/provider-tune'],
    requiredPermissions: ['fs:read'],
    requiredTools: ['read_file'],
    modelCompatibility: 'all',
    installSource: 'marketplace',
    instructions: [
      '### LLM Provider Routing Directive',
      'Analyze the current task requirements and evaluate appropriate model tiers (fast flash, reasoning, code specialist).',
    ].join('\n'),
    securityFlags: { isVerified: true, isSafe: true },
    stats: { downloads: 1250, rating: 4.75, invocations: 190 },
    icon: 'Cpu',
    createdAt: '2026-08-28T00:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },
];
